### ISSUE TITLE
distributed archive / archive search index hosting?

### ISSUE THREAD

**Issue by 00000o1** [dosyago/DownloadNet#107]
https://boredcaveman.xyz/post/0x1_dbless-torrent-website.html

**Comment by i5ik** [comment]
https://news.ycombinator.com/item?id=29917818

**Comment by 00000o1** [comment]
Do you want to work on this? 😁

it’s a very cool idea, and i think ipfs may almost be mature enough for it to be relatively fast.

am intermediate step, and alternative, is just serving the search engine on a public address and somehow making the archives serviceable from there too. I don’t think the latter is too hard, rather than reading them from disk. We just read them off the net work.

**Comment by 00000o1** [comment]
Anyway thanks @tomodachi94

**Comment by tomodachi94** [comment]
> Do you want to work on this?

I'm not super great at Node, but I can take a shot. I'm somewhat familiar with IPFS, and I'd love to use it in a project 🙂

Adding some more rationale:

This feature would very much help with the need for a decentralized web archival effort; currently, the majority of the web's archives are hosted on places like Archive.org, and some of the folks at places like Archiveteam view that as a potential problem (which spawned some initiatives like INTERNETARCHIVE.BAK that got shut down for unknown reasons.)

**Comment by 00000o1** [comment]
Agree! I like the idea of distributed archive. 

I think my focus is more on making federated search with this (where results pages can be backed up by archive so you never lose anything, as is implemented currently at DK~~ DiskerNet), where people can serve their own micro search engines on some topic where they have conducted extensive research. Like a custom searchable bibliography...

but I think the overarching need for archiving and now having the recognition that that needs to be distributed, is a very compelling case, and there's certainly a strong market for this. I like how DK works just in the browser, letting you serve pages as if you were browsing them online. Making I think a viable and personal alt for this distributed archive. 

Anyway, it's great to see your enthusiasm, and if you want to have a shot I'm happy to review and provide what help and guidance i'm able!

**Comment by tomodachi94** [comment]
Sounds like a good idea! Do you have a Matrix chatroom, an IRC channel, or a Discord server? I'd love to chat about this in real-time 🙂

**Comment by 00000o1** [comment]
Hmm, *that* sounds like a good idea! I have none of those. What do you recommend, and why?

**Comment by tomodachi94** [comment]
I recommend Matrix first, IRC second, XMPP third, and Discord last.

[Matrix](https://matrix.org) is an open-source federated chat protocol that is prominently used in open-source. I recommend this first because it can federate between servers and it's easy to 'bridge' to other protocols and platforms if you want it, and there's active development happening on it right now.

[IRC](https://en.wikipedia.org/wiki/IRC) is an open-source chat protocol that you've probably heard mentions of at least once. I recommend this second because it's open-source and it's very prominent in older open-source projects. However, it also comes with the risk of IP leaks, which I'm not a fan of.

[Discord](https://discord.com) is a closed-source chat platform that is also sometimes used for open-source projects. This one has a very good UX, but it's closed-off and there are concerns about it being spyware, so I rank it last.

There's also [XMPP](https://en.wikipedia.org/wiki/XMPP), which I would rank between Matrix and IRC. XMPP is also an open standard with federation, but there are concerns about it's feasibility for modern tasks like sharing large media.

**Comment by 00000o1** [comment]
This advice is awesome! I’ll look at starting at matrix room/whatever it’s called, and message you on it when i do! Thank you @tomodachi94 🥹

**Comment by tomodachi94** [comment]
Re: distributed archive 

Off-topic, but this is pretty cool: https://github.com/internetarchive/dweb-mirror

**Comment by 00000o1** [comment]
Thanks @tomodachi94 for adding interesting stuff! :)

**Comment by 00000o1** [comment]
I think this is also cool: https://gyrovague.com/2023/08/05/archive-today-on-the-trail-of-the-mysterious-guerrilla-archivist-of-the-internet/

**Comment by 00000o1** [comment]
I don't think we need something like WARC. For IPFS we don't need it. And as the current archive format already works, WARC is pointless. We don't need it, it's just overhead. We don't need WARC. It's pointless. We already have a working archive format. It's probably better than WARC in a lot of ways. It's designed specifically for this. And we don't need it for IPFS, we can implement that completely without WARC. WARC in this suggestion just like a pointless busy work or fake blocker or even procrastination to avoid getting into IPFS. That's all.
